# Generated by Django 4.2.4 on 2023-08-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0002_alter_searchkeyword_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchkeyword',
            name='id',
        ),
        migrations.AlterField(
            model_name='searchkeyword',
            name='keyword',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
