# Generated by Django 4.2.3 on 2023-08-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0003_remove_searchkeyword_id_alter_searchkeyword_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchkeyword',
            options={'ordering': ['-jumlah']},
        ),
    ]
