# Generated by Django 4.2.3 on 2023-08-30 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0004_alter_searchkeyword_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterBarang',
            fields=[
                ('barang_sku', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='Kode SKU')),
                ('barang_nama', models.CharField(default='', max_length=100, verbose_name='Nama Barang')),
                ('barang_deskripsi', models.TextField(max_length=1000, verbose_name='Deskripsi Barang')),
                ('barang_foto1', models.ImageField(upload_to='barang', verbose_name='Gambar Barang #1')),
                ('barang_foto2', models.ImageField(upload_to='barang', verbose_name='Gambar Barang #2')),
                ('barang_foto3', models.ImageField(upload_to='barang', verbose_name='Gambar Barang #3')),
                ('barang_foto4', models.ImageField(upload_to='barang', verbose_name='Gambar Barang #4')),
                ('barang_foto5', models.ImageField(upload_to='barang', verbose_name='Gambar Barang #5')),
                ('barang_foto6', models.ImageField(upload_to='barang', verbose_name='Gambar Barang #6')),
                ('barang_harga', models.PositiveBigIntegerField(default=0, verbose_name='Harga Barang (Rupiah)')),
                ('barang_arsip', models.BooleanField(default=False, verbose_name='Barang Diarsipkan? (arsip->tidak ditampilkan)')),
                ('barang_new', models.BooleanField(default=True, verbose_name='Barang di set NEW?')),
                ('barang_disc', models.PositiveSmallIntegerField(default=0, verbose_name='Discount Harga Barang (Rupiah)')),
                ('barang_disc_aktif', models.BooleanField(default=False, verbose_name='Discount diaktifkan?')),
                ('barang_ongkir', models.PositiveIntegerField(default=0, verbose_name='Gratis Ongkir Barang (Rupiah)')),
                ('barang_ongkir_aktif', models.BooleanField(default=False, verbose_name='Gratis Ongkir diaktifkan?')),
            ],
            options={
                'ordering': ['barang_nama', 'barang_sku'],
                'unique_together': {('barang_nama', 'barang_sku')},
            },
        ),
        migrations.CreateModel(
            name='variasiWarna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang_warna', models.CharField(max_length=50, verbose_name='Nama Variasi Warna')),
                ('barang_jumlah', models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah Barang')),
                ('barang_sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Nama Barang')),
            ],
            options={
                'ordering': ['barang_sku', 'barang_warna'],
                'unique_together': {('barang_sku', 'barang_warna')},
            },
        ),
        migrations.CreateModel(
            name='kategoriBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang_kategori', models.CharField(max_length=50, verbose_name='Nama Kategori Barang')),
                ('barang_sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Nama Barang')),
            ],
            options={
                'ordering': ['barang_sku', 'barang_kategori'],
                'unique_together': {('barang_sku', 'barang_kategori')},
            },
        ),
    ]
