# Generated by Django 4.2.3 on 2023-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0005_masterbarang_variasiwarna_kategoribarang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoribarang',
            name='id',
        ),
        migrations.AlterField(
            model_name='kategoribarang',
            name='barang_kategori',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nama Kategori Barang'),
        ),
    ]
