# Generated by Django 4.2.3 on 2023-08-31 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0007_alter_kategoribarang_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='variasiVisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang_visor', models.CharField(max_length=50, verbose_name='Nama Variasi Warna')),
                ('barang_jumlah', models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah Barang')),
                ('barang_sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Nama Barang')),
            ],
            options={
                'ordering': ['barang_sku', 'barang_visor'],
                'unique_together': {('barang_sku', 'barang_visor')},
            },
        ),
        migrations.CreateModel(
            name='variasiUkuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang_ukuran', models.CharField(max_length=50, verbose_name='Nama Variasi Warna')),
                ('barang_jumlah', models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah Barang')),
                ('barang_sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Nama Barang')),
            ],
            options={
                'ordering': ['barang_sku', 'barang_ukuran'],
                'unique_together': {('barang_sku', 'barang_ukuran')},
            },
        ),
    ]
