# Generated by Django 4.2.3 on 2023-08-31 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0008_variasivisor_variasiukuran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variasiukuran',
            name='barang_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Ukuran Barang'),
        ),
        migrations.AlterField(
            model_name='variasivisor',
            name='barang_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Jenis Visor Barang'),
        ),
    ]
