# Generated by Django 4.2.3 on 2023-08-31 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0009_alter_variasiukuran_barang_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='etalase',
            fields=[
                ('etalase_kode', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='Kode Etalase')),
                ('etalase_nama', models.CharField(default='', max_length=200, verbose_name='Nama Etalase')),
            ],
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.kategoribarang', verbose_name='Kategori Barang'),
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='barang_etalase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='administrasi.etalase', verbose_name='Etalase Barang'),
            preserve_default=False,
        ),
    ]
