# Generated by Django 4.2.3 on 2023-08-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0010_etalase_alter_masterbarang_barang_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoribarang',
            name='barang_kategori_gambar',
            field=models.ImageField(blank=True, null=True, upload_to='kategori_gambar', verbose_name='Gambar Kategori'),
        ),
        migrations.AddField(
            model_name='variasivisor',
            name='barang_visor_gambar',
            field=models.ImageField(blank=True, null=True, upload_to='visor', verbose_name='Gambar Visor'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_foto1',
            field=models.ImageField(blank=True, null=True, upload_to='barang', verbose_name='Gambar Barang #1'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_foto2',
            field=models.ImageField(blank=True, null=True, upload_to='barang', verbose_name='Gambar Barang #2'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_foto3',
            field=models.ImageField(blank=True, null=True, upload_to='barang', verbose_name='Gambar Barang #3'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_foto4',
            field=models.ImageField(blank=True, null=True, upload_to='barang', verbose_name='Gambar Barang #4'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_foto5',
            field=models.ImageField(blank=True, null=True, upload_to='barang', verbose_name='Gambar Barang #5'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_foto6',
            field=models.ImageField(blank=True, null=True, upload_to='barang', verbose_name='Gambar Barang #6'),
        ),
        migrations.AlterField(
            model_name='variasiukuran',
            name='barang_ukuran',
            field=models.CharField(max_length=50, verbose_name='Nama Variasi Ukuran'),
        ),
        migrations.AlterField(
            model_name='variasivisor',
            name='barang_visor',
            field=models.CharField(max_length=50, verbose_name='Nama Variasi Visor'),
        ),
    ]
