# Generated by Django 4.2.3 on 2023-08-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0011_kategoribarang_barang_kategori_gambar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='barang_dicari',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah HIT'),
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='barang_terjual',
            field=models.PositiveIntegerField(default=0, verbose_name='Barang Jumlah Terjual'),
        ),
    ]
