# Generated by Django 4.2.3 on 2023-09-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0012_masterbarang_barang_dicari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='merek',
            fields=[
                ('merek_kode', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Kode Merek')),
                ('merek_nama', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['merek_nama'],
            },
        ),
        
    ]
