# Generated by Django 4.2.3 on 2023-09-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0013_merek_masterbarang_barang_merek'),
    ]

    operations = [
        
    ]
