# Generated by Django 4.2.3 on 2023-09-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0015_remove_merek_merek_kode_merek_merek_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='barang_merek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='administrasi.merek'),
        ),
    ]
