# Generated by Django 4.2.3 on 2023-09-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0016_masterbarang_barang_merek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_merek',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='administrasi.merek'),
            preserve_default=False,
        ),
    ]
