# Generated by Django 4.2.3 on 2023-09-04 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrasi', '0017_alter_masterbarang_barang_merek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbarang',
            name='barang_etalase',
        ),
        migrations.CreateModel(
            name='chatHeader',
            fields=[
                ('chat_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chatBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_message', models.TextField(max_length=500)),
                ('chat_time', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.chatheader')),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
