# Generated by Django 4.2.3 on 2023-09-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0018_remove_masterbarang_barang_etalase_chatheader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='barang_merek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='administrasi.merek'),
        ),
    ]
