# Generated by Django 4.2.3 on 2023-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0021_alamatrumah'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailKonfirm',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=8)),
                ('exp', models.DateTimeField()),
            ],
        ),
    ]
