# Generated by Django 4.2.3 on 2023-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0022_emailkonfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='barang_berat',
            field=models.PositiveIntegerField(default=0, verbose_name='Berat Barang dalam Gram'),
        ),
    ]
