# Generated by Django 4.2.3 on 2023-09-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrasi', '0019_alter_masterbarang_barang_merek'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_jumlah', models.PositiveIntegerField(default=0)),
                ('shopping_barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Kode Barang')),
            ],
        ),
    ]
