# Generated by Django 4.2.3 on 2023-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='shopping_visor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='shopping_warna',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
