# Generated by Django 4.2.3 on 2023-09-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0002_shoppingcart_shopping_visor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['id']},
        ),
    ]
