# Generated by Django 4.2.3 on 2023-09-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0020_remove_variasiukuran_barang_jumlah_and_more'),
        ('penjualan', '0005_wishlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist_item',
            name='id',
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='kode_barang',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='administrasi.masterbarang', verbose_name='Barang Wishlist'),
            preserve_default=False,
        ),
    ]
