# Generated by Django 4.2.3 on 2023-09-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0020_remove_variasiukuran_barang_jumlah_and_more'),
        ('penjualan', '0006_remove_wishlist_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist_item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='kode_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Barang Wishlist'),
        ),
    ]
