# Generated by Django 4.2.3 on 2023-09-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0020_remove_variasiukuran_barang_jumlah_and_more'),
        ('penjualan', '0007_wishlist_item_id_alter_wishlist_item_kode_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_Ongkir',
            fields=[
                ('voucher_kode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('voucher_nama', models.CharField(max_length=200)),
                ('voucher_valid', models.DateField()),
                ('voucher_min_belanja', models.PositiveBigIntegerField(default=0)),
                ('voucher_nilai', models.PositiveIntegerField(default=0)),
                ('voucher_aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buying_Header',
            fields=[
                ('buying_kode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('buying_kirim_resi', models.CharField(blank=True, max_length=200, null=True)),
                ('buying_kirim_ekspedisi', models.CharField(blank=True, max_length=200, null=True)),
                ('buying_voucher_ongkir', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='penjualan.voucher_ongkir')),
            ],
        ),
        migrations.CreateModel(
            name='Buying_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_jumlah', models.PositiveIntegerField(default=0)),
                ('buying_warna', models.CharField(max_length=200)),
                ('buying_visor', models.CharField(max_length=200)),
                ('buying_pesan', models.CharField(max_length=200)),
                ('buying_barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterbarang', verbose_name='Kode Barang')),
                ('buying_kode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='penjualan.buying_header')),
            ],
        ),
    ]
