# Generated by Django 4.2.3 on 2023-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0008_voucher_ongkir_buying_header_buying_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_header',
            name='buying_total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buying_header',
            name='buying_kode',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
