# Generated by Django 4.2.3 on 2023-09-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0009_buying_header_buying_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buying_detail',
            old_name='buying_jumlah',
            new_name='buying_total',
        ),
    ]
