# Generated by Django 4.2.3 on 2023-09-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0010_rename_buying_jumlah_buying_detail_buying_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buying_detail',
            old_name='buying_total',
            new_name='buying_jumlah',
        ),
        migrations.RemoveField(
            model_name='buying_header',
            name='buying_voucher_ongkir',
        ),
    ]
