# Generated by Django 4.2.3 on 2023-09-12 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0011_rename_buying_total_buying_detail_buying_jumlah_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buying_header',
            options={'ordering': ['-buying_order']},
        ),
        migrations.AlterModelOptions(
            name='voucher_ongkir',
            options={'ordering': ['-voucher_tanggal']},
        ),
        migrations.AddField(
            model_name='buying_header',
            name='buying_order',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher_ongkir',
            name='voucher_tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buying_header',
            name='buying_total',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
