# Generated by Django 4.2.3 on 2023-09-12 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0012_alter_buying_header_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buying_header',
            options={'ordering': ['-buying_time']},
        ),
        migrations.AlterModelOptions(
            name='voucher_ongkir',
            options={'ordering': ['-voucher_time']},
        ),
        migrations.RemoveField(
            model_name='buying_header',
            name='buying_order',
        ),
        migrations.RemoveField(
            model_name='voucher_ongkir',
            name='voucher_tanggal',
        ),
        migrations.AddField(
            model_name='buying_header',
            name='buying_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher_ongkir',
            name='voucher_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
