# Generated by Django 4.2.3 on 2023-09-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0015_klaim_voucher_ongkir_voucher_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='klaim_voucher_ongkir',
            name='voucher_nama',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
