# Generated by Django 4.2.3 on 2023-09-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penjualan', '0016_klaim_voucher_ongkir_voucher_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_header',
            name='buying_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klaim_voucher_ongkir',
            name='voucher_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='shopping_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
