# Generated by Django 4.2.3 on 2023-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0018_wishlist_item_wish_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaim_voucher_ongkir',
            name='voucher_klaim',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
