# Generated by Django 4.2.3 on 2023-09-18 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penjualan', '0019_alter_klaim_voucher_ongkir_voucher_klaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Nama', models.CharField(max_length=200)),
                ('User_Alamat', models.CharField(max_length=200)),
                ('User_Telpon', models.CharField(max_length=200)),
                ('User_Provinsi', models.CharField(max_length=200)),
                ('User_Provinsi_id', models.CharField(max_length=10)),
                ('User_Kabupaten', models.CharField(max_length=200)),
                ('User_Kabupaten_id', models.CharField(max_length=10)),
                ('User_Kabupaten_tipe', models.CharField(max_length=200)),
                ('User_Kode_Pos', models.CharField(max_length=10)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
